import functools
from _typeshed import Incomplete

KAGGLE_NOTEBOOK_ENV_VAR_NAME: str
KAGGLE_DATA_PROXY_URL_ENV_VAR_NAME: str
KAGGLE_TOKEN_KEY_DIR_ENV_VAR_NAME: str
logger: Incomplete

def is_in_colab_notebook() -> bool: ...
def is_in_kaggle_notebook() -> bool: ...
@functools.cache
def read_kaggle_build_date() -> str: ...
def search_lib_in_call_stack(lib_name: str) -> str | None: ...
