import abc
from dataclasses import dataclass
from kagglehub.config import get_kaggle_api_endpoint as get_kaggle_api_endpoint

NUM_VERSIONED_DATASET_PARTS: int
NUM_UNVERSIONED_DATASET_PARTS: int
NUM_VERSIONED_MODEL_PARTS: int
NUM_UNVERSIONED_MODEL_PARTS: int
NUM_VERSIONED_NOTEBOOK_PARTS: int
NUM_UNVERSIONED_NOTEBOOK_PARTS: int

@dataclass(frozen=True)
class ResourceHandle(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def to_url(self) -> str: ...

@dataclass(frozen=True)
class ModelHandle(ResourceHandle):
    owner: str
    model: str
    framework: str
    variation: str
    version: int | None
    def is_versioned(self) -> bool: ...
    def with_version(self, version: int) -> ModelHandle: ...
    def to_url(self) -> str: ...

@dataclass(frozen=True)
class DatasetHandle(ResourceHandle):
    owner: str
    dataset: str
    version: int | None = ...
    def is_versioned(self) -> bool: ...
    def with_version(self, version: int) -> DatasetHandle: ...
    def to_url(self) -> str: ...

@dataclass(frozen=True)
class CompetitionHandle(ResourceHandle):
    competition: str
    def to_url(self) -> str: ...

@dataclass(frozen=True)
class NotebookHandle(ResourceHandle):
    owner: str
    notebook: str
    version: int | None = ...
    def is_versioned(self) -> bool: ...
    def with_version(self, version: int) -> NotebookHandle: ...
    def to_url(self) -> str: ...

class UtilityScriptHandle(NotebookHandle): ...

class PackageHandle(NotebookHandle):
    def with_version(self, version: int) -> PackageHandle: ...

def parse_dataset_handle(handle: str) -> DatasetHandle: ...
def parse_model_handle(handle: str) -> ModelHandle: ...
def parse_competition_handle(handle: str) -> CompetitionHandle: ...
def parse_notebook_handle(handle: str) -> NotebookHandle: ...
def parse_utility_script_handle(handle: str) -> UtilityScriptHandle: ...
def parse_package_handle(handle: str) -> PackageHandle: ...
