from _typeshed import Incomplete

class KaggleApi:
    api_client: Incomplete
    def __init__(self, api_client=None) -> None: ...
    def competition_download_leaderboard(self, id): ...
    def competition_view_leaderboard(self, id): ...
    def competitions_data_download_file(self, id, file_name): ...
    def competitions_data_download_files(self, id): ...
    def competitions_data_list_files(self, id): ...
    def competitions_list(
        self, group=None, category=None, sort_by=None, page: int = 1, search=None
    ): ...
    def competitions_submissions_list(self, id, page: int = 0): ...
    def competitions_submissions_submit(
        self, blob_file_tokens, submission_description, id
    ) -> None: ...
    def competitions_submissions_upload(
        self, file, guid, content_length, last_modified_date_utc
    ) -> None: ...
    def competitions_submissions_url(
        self, id, content_length, last_modified_date_utc
    ) -> None: ...
    def create_inbox_file(self, create_inbox_file_request) -> None: ...
    def datasets_create_new(self, request) -> None: ...
    def datasets_create_version_by_id(
        self, id, dataset_new_version_request, **kwargs
    ) -> None: ...
    def datasets_download(
        self, owner_slug, dataset_slug, dataset_version_number=None
    ): ...
    def datasets_download_file(
        self, owner_slug, dataset_slug, file_name, dataset_version_number=None
    ): ...
    def datasets_list(
        self,
        sort_by=None,
        size=None,
        file_type=None,
        license_name=None,
        tag_ids=None,
        search=None,
        user=None,
        mine: bool = False,
        page: int = 1,
        max_size=None,
        min_size=None,
    ): ...
    def datasets_status(self, owner_slug, dataset_slug, **kwargs): ...
    def delete_model(self, owner_slug, model_slug): ...
    def delete_model_instance(
        self, owner_slug, model_slug, framework, instance_slug
    ): ...
    def delete_model_instance_version(
        self, owner_slug, model_slug, framework, instance_slug, version_number
    ): ...
    def get_model(self, owner_slug, model_slug): ...
    def get_model_instance(self, owner_slug, model_slug, framework, instance_slug): ...
    def kernel_output(self, user_name, kernel_slug): ...
    def kernel_pull(self, user_name, kernel_slug): ...
    def kernel_push(self, kernel_push_request): ...
    def kernel_status(self, user_name, kernel_slug): ...
    def kernels_list(
        self,
        page: int = 1,
        page_size: int = 20,
        dataset=None,
        competition=None,
        parent_kernel=None,
        search=None,
        group: str = "everyone",
        user=None,
        language=None,
        kernel_type=None,
        output_type=None,
        sort_by=None,
    ): ...
    def metadata_get(self, owner_slug, dataset_slug): ...
    def metadata_post(self, owner_slug, dataset_slug, settings, request): ...
    def model_instance_versions_download(
        self, owner_slug, model_slug, framework, instance_slug, version_number
    ): ...
    def models_create_instance(
        self, owner_slug, model_slug, model_new_instance_request
    ) -> None: ...
    def models_create_instance_version(
        self,
        owner_slug,
        model_slug,
        framework,
        instance_slug,
        model_instance_new_version_request,
    ) -> None: ...
    def models_create_new(self, model_new_request): ...
    def models_list(
        self,
        sort_by=None,
        search=None,
        owner=None,
        page_size: int = 20,
        page_token=None,
    ): ...
    def update_model(self, owner_slug, model_slug, model_update_request): ...
    def update_model_instance(
        self,
        owner_slug,
        model_slug,
        framework,
        instance_slug,
        model_instance_update_request,
    ): ...
    def upload_file(self, start_blob_upload_request) -> None: ...
