from _typeshed import Incomplete

class Configuration:
    host: Incomplete
    api_key: Incomplete
    api_key_prefix: Incomplete
    username: str
    password: str
    logger: Incomplete
    logger_stream_handler: Incomplete
    logger_file_handler: Incomplete
    def __init__(self) -> None: ...
    @property
    def logger_file(self): ...
    @logger_file.setter
    def logger_file(self, value) -> None: ...
    @property
    def debug(self): ...
    @debug.setter
    def debug(self, value) -> None: ...
    @property
    def logger_format(self): ...
    logger_formatter: Incomplete
    @logger_format.setter
    def logger_format(self, value) -> None: ...
    def get_api_key_with_prefix(self, identifier): ...
    def get_basic_auth_token(self): ...
    def auth_settings(self): ...
    def to_debug_report(self): ...
