from _typeshed import Incomplete

class KernelPushRequest:
    project_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        id=None,
        slug=None,
        new_title=None,
        text=None,
        language=None,
        kernel_type=None,
        is_private=None,
        enable_gpu=None,
        enable_tpu=None,
        enable_internet=None,
        dataset_data_sources=None,
        competition_data_sources=None,
        kernel_data_sources=None,
        model_data_sources=None,
        category_ids=None,
        docker_image_pinning_type=None,
    ) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id) -> None: ...
    @property
    def slug(self): ...
    @slug.setter
    def slug(self, slug) -> None: ...
    @property
    def new_title(self): ...
    @new_title.setter
    def new_title(self, new_title) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    @property
    def language(self): ...
    @language.setter
    def language(self, language) -> None: ...
    @property
    def kernel_type(self): ...
    @kernel_type.setter
    def kernel_type(self, kernel_type) -> None: ...
    @property
    def is_private(self): ...
    @is_private.setter
    def is_private(self, is_private) -> None: ...
    @property
    def enable_gpu(self): ...
    @enable_gpu.setter
    def enable_gpu(self, enable_gpu) -> None: ...
    @property
    def enable_tpu(self): ...
    @enable_tpu.setter
    def enable_tpu(self, enable_tpu) -> None: ...
    @property
    def enable_internet(self): ...
    @enable_internet.setter
    def enable_internet(self, enable_internet) -> None: ...
    @property
    def dataset_data_sources(self): ...
    @dataset_data_sources.setter
    def dataset_data_sources(self, dataset_data_sources) -> None: ...
    @property
    def competition_data_sources(self): ...
    @competition_data_sources.setter
    def competition_data_sources(self, competition_data_sources) -> None: ...
    @property
    def kernel_data_sources(self): ...
    @kernel_data_sources.setter
    def kernel_data_sources(self, kernel_data_sources) -> None: ...
    @property
    def model_data_sources(self): ...
    @model_data_sources.setter
    def model_data_sources(self, model_data_sources) -> None: ...
    @property
    def category_ids(self): ...
    @category_ids.setter
    def category_ids(self, category_ids) -> None: ...
    @property
    def docker_image_pinning_type(self): ...
    @docker_image_pinning_type.setter
    def docker_image_pinning_type(self, docker_image_pinning_type) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
