from _typeshed import Incomplete

class ModelInstanceUpdateRequest:
    project_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        overview=None,
        usage=None,
        license_name: str = "Apache 2.0",
        fine_tunable: bool = True,
        training_data=None,
        model_instance_type=None,
        base_model_instance=None,
        external_base_model_url=None,
        update_mask=None,
    ) -> None: ...
    @property
    def overview(self): ...
    @overview.setter
    def overview(self, overview) -> None: ...
    @property
    def usage(self): ...
    @usage.setter
    def usage(self, usage) -> None: ...
    @property
    def license_name(self): ...
    @license_name.setter
    def license_name(self, license_name) -> None: ...
    @property
    def fine_tunable(self): ...
    @fine_tunable.setter
    def fine_tunable(self, fine_tunable) -> None: ...
    @property
    def training_data(self): ...
    @training_data.setter
    def training_data(self, training_data) -> None: ...
    @property
    def model_instance_type(self): ...
    @model_instance_type.setter
    def model_instance_type(self, model_instance_type) -> None: ...
    @property
    def base_model_instance(self): ...
    @base_model_instance.setter
    def base_model_instance(self, base_model_instance) -> None: ...
    @property
    def external_base_model_url(self): ...
    @external_base_model_url.setter
    def external_base_model_url(self, external_base_model_url) -> None: ...
    @property
    def update_mask(self): ...
    @update_mask.setter
    def update_mask(self, update_mask) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
