from _typeshed import Incomplete
from kaggle.models.upload_file import UploadFile as UploadFile

class ModelInstanceNewVersionRequest:
    project_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, version_notes=None, files=None) -> None: ...
    @property
    def version_notes(self): ...
    @version_notes.setter
    def version_notes(self, version_notes) -> None: ...
    @property
    def files(self): ...
    @files.setter
    def files(self, files) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
