from _typeshed import Incomplete

class ModelNewRequest:
    project_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        owner_slug=None,
        slug=None,
        title=None,
        subtitle=None,
        is_private: bool = True,
        description: str = "",
        publish_time=None,
        provenance_sources: str = "",
    ) -> None: ...
    @property
    def owner_slug(self): ...
    @owner_slug.setter
    def owner_slug(self, owner_slug) -> None: ...
    @property
    def slug(self): ...
    @slug.setter
    def slug(self, slug) -> None: ...
    @property
    def title(self): ...
    @title.setter
    def title(self, title) -> None: ...
    @property
    def subtitle(self): ...
    @subtitle.setter
    def subtitle(self, subtitle) -> None: ...
    @property
    def is_private(self): ...
    @is_private.setter
    def is_private(self, is_private) -> None: ...
    @property
    def description(self): ...
    @description.setter
    def description(self, description) -> None: ...
    @property
    def publish_time(self): ...
    @publish_time.setter
    def publish_time(self, publish_time) -> None: ...
    @property
    def provenance_sources(self): ...
    @provenance_sources.setter
    def provenance_sources(self, provenance_sources) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
