from _typeshed import Incomplete
from kaggle.models.upload_file import UploadFile as UploadFile

class ModelNewInstanceRequest:
    project_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        instance_slug=None,
        framework=None,
        overview=None,
        usage=None,
        license_name: str = "Apache 2.0",
        fine_tunable: bool = True,
        training_data=None,
        model_instance_type=None,
        base_model_instance=None,
        external_base_model_url=None,
        files=None,
    ) -> None: ...
    @property
    def instance_slug(self): ...
    @instance_slug.setter
    def instance_slug(self, instance_slug) -> None: ...
    @property
    def framework(self): ...
    @framework.setter
    def framework(self, framework) -> None: ...
    @property
    def overview(self): ...
    @overview.setter
    def overview(self, overview) -> None: ...
    @property
    def usage(self): ...
    @usage.setter
    def usage(self, usage) -> None: ...
    @property
    def license_name(self): ...
    @license_name.setter
    def license_name(self, license_name) -> None: ...
    @property
    def fine_tunable(self): ...
    @fine_tunable.setter
    def fine_tunable(self, fine_tunable) -> None: ...
    @property
    def training_data(self): ...
    @training_data.setter
    def training_data(self, training_data) -> None: ...
    @property
    def model_instance_type(self): ...
    @model_instance_type.setter
    def model_instance_type(self, model_instance_type) -> None: ...
    @property
    def base_model_instance(self): ...
    @base_model_instance.setter
    def base_model_instance(self, base_model_instance) -> None: ...
    @property
    def external_base_model_url(self): ...
    @external_base_model_url.setter
    def external_base_model_url(self, external_base_model_url) -> None: ...
    @property
    def files(self): ...
    @files.setter
    def files(self, files) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
