from _typeshed import Incomplete

class ModelUpdateRequest:
    project_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        title=None,
        subtitle=None,
        is_private: bool = True,
        description: str = "",
        publish_time=None,
        provenance_sources: str = "",
        update_mask=None,
    ) -> None: ...
    @property
    def title(self): ...
    @title.setter
    def title(self, title) -> None: ...
    @property
    def subtitle(self): ...
    @subtitle.setter
    def subtitle(self, subtitle) -> None: ...
    @property
    def is_private(self): ...
    @is_private.setter
    def is_private(self, is_private) -> None: ...
    @property
    def description(self): ...
    @description.setter
    def description(self, description) -> None: ...
    @property
    def publish_time(self): ...
    @publish_time.setter
    def publish_time(self, publish_time) -> None: ...
    @property
    def provenance_sources(self): ...
    @provenance_sources.setter
    def provenance_sources(self, provenance_sources) -> None: ...
    @property
    def update_mask(self): ...
    @update_mask.setter
    def update_mask(self, update_mask) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
