from _typeshed import Incomplete

class StartBlobUploadRequest:
    project_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        type=None,
        name=None,
        content_length=None,
        content_type=None,
        last_modified_epoch_seconds=None,
    ) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None: ...
    @property
    def content_length(self): ...
    @content_length.setter
    def content_length(self, content_length) -> None: ...
    @property
    def content_type(self): ...
    @content_type.setter
    def content_type(self, content_type) -> None: ...
    @property
    def last_modified_epoch_seconds(self): ...
    @last_modified_epoch_seconds.setter
    def last_modified_epoch_seconds(self, last_modified_epoch_seconds) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
