from _typeshed import Incomplete

class StartBlobUploadResponse:
    project_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, token=None, create_url=None) -> None: ...
    @property
    def token(self): ...
    @token.setter
    def token(self, token) -> None: ...
    @property
    def create_url(self): ...
    @create_url.setter
    def create_url(self, create_url) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
