from _typeshed import Incomplete
from kaggle.models.dataset_column import DatasetColumn as DatasetColumn

class UploadFile:
    column_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, token=None, description=None, columns=None) -> None: ...
    @property
    def token(self): ...
    @token.setter
    def token(self, token) -> None: ...
    @property
    def description(self): ...
    @description.setter
    def description(self, description) -> None: ...
    @property
    def columns(self): ...
    @columns.setter
    def columns(self, columns) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
